name: bayesian-modelling-tutorial
channels:
- defaults
- conda-forge
- ericmjl
dependencies:
- python=3.7
- jupyter
- pymc3
- seaborn
- matplotlib
- numpy
- scipy
- pandas
- jupyterlab
- tqdm
- missingno
- scikit-learn
- cython
- nodejs
- pyjanitor
- xarray
- pandoc
- black
- nbstripout
- pylint
- theano>=1.0.4
- pip:
  - arviz
