name: bayesian-modelling-tutorial
channels:
- conda-forge
- defaults
- anaconda
- ericmjl
dependencies:
- python>=3.8
- jupyter
- jupyterlab>=3.0
- pymc=4.0
- pip
- seaborn
- matplotlib
- numpy
- scipy
- pandas
- tqdm
- missingno
- scikit-learn
- nodejs
- pyjanitor
- xarray
- pandoc
- black
- nbstripout
- pylint
- arviz
- theano
- ipykernel
- hvplot
- bokeh
- holoviews
- mkl
- mkl-service
- pre-commit
- networkx
- mamba
- "python-graphviz"
- pyprojroot
- faker
- pip:
  - mkdocs
  - mkdocs-material
  - mknotebooks
  - daft
  - gapminder
  # Need to add pip install from github for repo, so solutions can be executed.